const unitSpecs=[
['sentence-village','🏘️','句子村','Sentence Village','看懂一句话的骨架',['什么是句子','主语','动词','宾语','表语','补语','五大基本句型']],
['noun-city','🏙️','名词城','Noun City','认识人、地点、东西和冠词',['什么是名词','人、地点、东西','可数名词','不可数名词','单数和复数','a / an / the']],
['pronoun-island','🏝️','代词岛','Pronoun Island','用小词代替名字',['I / you / he / she / it','we / they','me / him / her / us / them','my / your / his / her / their','this / that']],
['verb-town','🚂','动词镇','Verb Town','认识动词和动词变化',['be 动词','实义动词','助动词','第三人称单数','动词过去式','动词 ing 形式']],
['tense-forest','🌲','时态森林','Tense Forest','用时间线看动词',['一般现在时','现在进行时','一般过去时','一般将来时','四种基础时态对比']],
['adjective-garden','🌷','形容词花园','Adjective Garden','描述样子和比较',['什么是形容词','形容词修饰名词','be + 形容词','比较级','最高级']],
['preposition-valley','⛰️','介词峡谷','Preposition Valley','说清时间和位置',['in','on','at','under','behind','near','时间介词','地点介词']],
['sentence-maze','🧩','句型迷宫','Sentence Maze','学习提问、否定和从句',['一般疑问句','特殊疑问句','否定句','there be 句型','并列句','宾语从句入门']]
];
const levelOf=i=>i%5===0?'challenge':i%3===0?'junior':'primary';
const stageOf=i=>i<16?'basic':i<34?'advanced':'power';
const keyBank={
'sentence-village':['sentence','subject','verb','object','predicative','complement','pattern'],
'noun-city':['noun','person','apple','water','dogs','an'],
'pronoun-island':['he','they','him','my','this'],
'verb-town':['is','read','do','goes','played','running'],
'tense-forest':['plays','is reading','visited','will go','now'],
'adjective-garden':['happy','red','tall','taller','the tallest'],
'preposition-valley':['in','on','at','under','behind','near','on','under'],
'sentence-maze':['Do','Where','not','is','and','that']
};
const sentenceBank=[
'Tom reads books.','She is happy.','We practice English.','The cat sleeps.','I like music.','They play football.','The book is on the desk.','Do you like apples?'
];
const units=unitSpecs.map((u,ui)=>({id:u[0],emoji:u[1],title:u[2],place:u[3],description:u[4],lessons:u[5].map((title,li)=>{const id=title.toLowerCase().replaceAll(' ','-').replaceAll('/','-').replace(/[^\w-]/g,'')||`${u[0]}-${li}`;const key=(keyBank[u[0]]||['English'])[li]||'English';const simple=`${title} = 先用一个小规则看懂句子。`;const examples=[sentenceBank[(ui+li)%sentenceBank.length],sentenceBank[(ui+li+2)%sentenceBank.length],sentenceBank[(ui+li+4)%sentenceBank.length]];return{id:`${u[0]}-${id}`,unitId:u[0],unitTitle:u[2],title,level:levelOf(ui*8+li),stage:stageOf(ui*8+li),simple,kid:`把“${title}”当成一块语法积木，先看例句，再做练习。`,cn:`本课用短句理解 ${title}，不背长定义。`,tip:`看到 ${title}，先找句子关键点。`,examples,answer:key,idx:li+1}})}));
const lessons=units.flatMap(u=>u.lessons);
function makeQs(l){const a=l.answer, ex=l.examples;const base=`${l.unitId}-${l.id}`;return[
['choice',`Which sentence is a good English example?`,[ex[0],'A blue bag','Very quickly'],ex[0]],['choice',`Choose the English key word.`,[a,'run','happy','table'],a],['fill',`Type the English key word for this lesson.`,[],a],['fill',`Fill with an English answer: ${a.includes(' ')?'___':a.replace(a,'___')}`,[],a],['tf',`True or false: this lesson uses short English examples.`,[],'true'],['order',`Put the words in order: ${ex[1]}`,ex[1].replace('.','').split(' ').reverse(),ex[1].replace('.','').split(' ')],['match',`Match English examples to key words.`,ex,{[ex[0]]:a,[ex[1]]:'example',[ex[2]]:'practice'}],['choice',`Choose an English practice sentence.`,[ex[2],'大 in 日 on 点 at','过去动词换衣服'],ex[2]],['detective',`Grammar Detective: tap the English key word.`,[a,'Tom','books','happy'],a],['detective',`Grammar Detective: tap the action word.`,ex[2].replace('.','').split(' '),'practice'],['choice',`Mini quiz: best English example.`,[ex[0],'Under the desk','A red apple'],ex[0]],['tf',`Mini quiz: English examples should stay in English.`,[],'true'],['order',`Mini quiz order: ${ex[2]}`,ex[2].replace('.','').split(' ').reverse(),ex[2].replace('.','').split(' ')],['fill',`Mini quiz fill: ${ex[1].replace('example','___')}`,[],'example'],['choice',`10 second challenge: choose the English answer.`, [a,'not','will','near'],a]
].map((x,i)=>({id:`${base}-q${i}`,lessonId:l.id,unitId:l.unitId,moduleTitle:l.unitTitle,type:x[0],prompt:x[1],options:x[2],answer:x[3],point:l.title,good:`太棒了！${l.title} 的关键点抓住了。`,bad:`再想想：${l.simple}`}))}
const questions=lessons.flatMap(makeQs);
const badgeDefs=[['all-8','八大地图探索家','🗺️'],['q100','百题训练家','💯'],['detective','语法侦探','🔎'],['wrong-clear','错题清零达人','✨']];
const state={view:'home',lesson:lessons[0].id,qi:0,mode:'lesson'};
const load=()=>JSON.parse(localStorage.gck2||'{"done":[],"answers":{},"wrong":{},"badges":[]}');
const save=p=>localStorage.gck2=JSON.stringify(p);
const norm=v=>Array.isArray(v)?v.join(' ').toLowerCase():typeof v==='object'?JSON.stringify(v):String(v??'').trim().toLowerCase();
const isOk=(q,a)=>norm(q.answer)===norm(a);
function award(p){if(p.done.length>=lessons.length)p.badges=[...new Set([...p.badges,'all-8'])];if(Object.values(p.answers).filter(Boolean).length>=100)p.badges=[...new Set([...p.badges,'q100'])];if(questions.filter(x=>x.type==='detective'&&p.answers[x.id]).length>=20)p.badges=[...new Set([...p.badges,'detective'])];if(Object.keys(p.wrong).length===0&&Object.keys(p.answers).length)p.badges=[...new Set([...p.badges,'wrong-clear'])];return p}
function daily(p){const wrong=Object.values(p.wrong).sort((a,b)=>b.mistakeCount-a.mistakeCount).map(r=>r.questionId);const recent=questions.filter(q=>p.done.slice(-5).includes(q.lessonId)).map(q=>q.id);const weak=questions.filter(q=>Object.values(p.wrong).some(r=>r.unitId===q.unitId)).map(q=>q.id);return [...new Set([...wrong,...recent,...weak,...questions.map(q=>q.id)])].slice(0,10).map(id=>questions.find(q=>q.id===id))}
function render(){const p=load();document.getElementById('app').innerHTML=`<header class=top><div class=top-inner><button class=brand onclick="go('home')"><span>Grammar Club Kids</span><strong>英语语法闯关乐园</strong></button><nav class=nav><button onclick="go('home')">首页</button><button onclick="go('wrong')">错题</button><button onclick="go('badges')">徽章</button></nav></div></header>${body(p)}<nav class=bottom><div><button onclick="go('home')">首页</button><button onclick="go('map')">地图</button><button onclick="startDaily()">复习</button><button onclick="go('wrong')">错题</button><button onclick="go('badges')">徽章</button></div></nav>`}
function body(p){if(state.view==='lesson')return lessonPage();if(state.view==='quiz')return quizPage(p);if(state.view==='wrong')return wrongPage(p);if(state.view==='badges')return badgesPage(p);return homePage(p)}
function homePage(p){const next=lessons.find(l=>!p.done.includes(l.id))||lessons[0],ans=Object.keys(p.answers).length,ok=Object.values(p.answers).filter(Boolean).length;return `<main><section class=hero><div class=hero-row><div><span class=pill>Grammar Kingdom</span><h1>英语语法王国</h1><p>第二阶段：8 个模块、48 个知识点、720 道练习题，每天 10 题复习。</p></div><button class=primary onclick="openLesson('${next.id}')">继续闯关 →</button></div></section><section class="grid stats"><div class=card><h3>今日任务</h3><p class=muted>做 10 道每日复习</p></div><div class=card><h3>当前进度</h3><p class=muted>${p.done.length}/${lessons.length} 关 · 正确率 ${ans?Math.round(ok/ans*100):0}%</p></div><button class=card onclick="go('wrong')"><h3>我的错题</h3><p class=muted>${Object.keys(p.wrong).length} 道需要复习</p></button><button class=card onclick="startDaily()"><h3>每日复习</h3><p class=muted>自动推荐 10 题</p></button></section>${map(p)}</main>`}
function map(p){return `<main><section class=card><h2>学习地图</h2><div class=grid>${units.map(u=>`<div class=unit><div class=unit-head><p>${u.emoji} ${u.place}</p><h3>${u.title}</h3><p>${u.description}</p></div><div class="grid map">${u.lessons.map(l=>`<button class="lesson-btn ${p.done.includes(l.id)?'done':''}" onclick="openLesson('${l.id}')"><span class=num>${p.done.includes(l.id)?'✓':l.idx}</span><span><span class=tag>${l.level}</span> <span class="tag stage">${l.stage}</span><strong style="display:block">${l.title}</strong><small>${l.simple}</small></span></button>`).join('')}</div></div>`).join('')}</div></section></main>`}
function lessonPage(){const l=lessons.find(x=>x.id===state.lesson);return `<main><button class=pill onclick="go('home')">返回地图</button><section class=card><p class=muted>${l.unitTitle}</p><h1>${l.title}</h1><span class=tag>${l.level}</span> <span class="tag stage">${l.stage}</span><div class="grid lesson-hero"><div class="card soft-sky"><b>一句话讲清楚</b><p class=big>${l.simple}</p></div><div class="card soft-peach"><b>口诀</b><p class=big>${l.tip}</p></div></div><div class="card soft-mint"><b>儿童化讲解</b><p>${l.kid}</p><p class=muted>${l.cn}</p></div><div class="grid example-grid">${l.examples.map(e=>`<div class=card><h3>${e}</h3><p class=muted>读例句，找关键点。</p></div>`).join('')}</div><button class=primary onclick="startQuiz()">开始练习</button></section></main>`}
function quizList(){return state.mode==='daily'?daily(load()):questions.filter(q=>q.lessonId===state.lesson)}
function quizPage(p){const list=quizList();if(state.qi>=list.length){if(state.mode==='lesson'){const pp=load();if(!pp.done.includes(state.lesson))pp.done.push(state.lesson);save(award(pp))}return `<main><section class=card style="text-align:center"><h1>${state.mode==='daily'?'每日复习完成':'小关卡完成'}</h1><p class=muted>休息一下眼睛，再继续下一关。</p><button class=primary onclick="go('home')">回到首页</button></section></main>`}const q=list[state.qi];let input='';if(['choice','timed'].includes(q.type))input=q.options.map(o=>`<button class=choice onclick="answer('${esc(o)}')">${o}</button>`).join('');if(q.type==='tf')input=`<button class=choice onclick="answer('true')">正确</button><button class=choice onclick="answer('false')">错误</button>`;if(q.type==='fill')input=`<input class=input id=fill placeholder="输入答案"><button class=primary onclick="answer(document.getElementById('fill').value)">提交</button>`;if(q.type==='order')input=`<div class=card id=order>点击词块排序</div><div class=row>${q.options.map(o=>`<button class=word onclick="pick('${esc(o)}')">${o}</button>`).join('')}</div><button class=primary onclick="answer(orderPicked)">提交</button>`;if(q.type==='detective')input=`<div class=row>${q.options.map(o=>`<button class=token onclick="answer('${esc(o)}')">${o}</button>`).join('')}</div>`;if(q.type==='match')input=`<div class=grid>${Object.keys(q.answer).map(k=>`<label class=card>${k}<select class=input data-match="${k}"><option></option>${Object.values(q.answer).map(v=>`<option>${v}</option>`).join('')}</select></label>`).join('')}</div><button class=primary onclick="answer(Object.fromEntries([...document.querySelectorAll('[data-match]')].map(s=>[s.dataset.match,s.value])))">提交配对</button>`;return `<main><button class=pill onclick="go('${state.mode==='daily'?'home':'lesson'}')">返回</button><section class=card><p class=muted>第 ${state.qi+1}/${list.length} 题 · ${q.moduleTitle||''} · ${q.point}</p><h2>${q.prompt}</h2><div class=grid>${input}</div><div id=fb></div></section></main>`}
let orderPicked=[];function pick(x){orderPicked.push(x);document.getElementById('order').textContent=orderPicked.join(' ')}
function answer(a){const p=load(),q=quizList()[state.qi],ok=isOk(q,a);p.answers[q.id]=ok;if(ok)delete p.wrong[q.id];else p.wrong[q.id]={questionId:q.id,unitId:q.unitId,lessonId:q.lessonId,moduleTitle:q.moduleTitle,prompt:q.prompt,wrongAnswer:norm(a),correctAnswer:norm(q.answer),knowledgePoint:q.point,mistakeCount:(p.wrong[q.id]?.mistakeCount||0)+1,lastMistakeAt:new Date().toISOString()};save(award(p));document.getElementById('fb').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><b>${ok?'太棒了！':'再想想'}</b><p>${ok?q.good:q.bad}</p>${ok?'':`<p>正确答案：${norm(q.answer)}</p>`}<button class=primary onclick="nextQ()">下一题</button></div>`}
function wrongPage(p){const r=Object.values(p.wrong).sort((a,b)=>b.mistakeCount-a.mistakeCount);const groups={};r.forEach(x=>{const k=`${x.moduleTitle} · ${x.knowledgePoint}`;(groups[k] ||= []).push(x)});return `<main><section class=card><h2>我的错题</h2><p class=muted>按模块和知识点分类，错误次数多的排前面。</p>${r.length?Object.entries(groups).map(([k,items])=>`<div class=card><h3>${k}</h3>${items.map(x=>`<div class=wrong><p>${x.prompt}</p><p>你的答案：${x.wrongAnswer}</p><p>正确答案：${x.correctAnswer}</p><p class=muted>错误 ${x.mistakeCount} 次</p><button class=pill onclick="review('${x.questionId}')">重新练习</button><button class=pill onclick="clearWrong('${x.questionId}')">已掌握</button></div>`).join('')}</div>`).join(''):'<div class="card soft-mint"><h2>今天没有错题</h2><p>继续闯关，保持这个状态。</p></div>'}</section></main>`}
function badgesPage(p){return `<main><section class=card><h2>我的徽章</h2><div class="grid map">${badgeDefs.map(b=>`<div class=card style="${p.badges.includes(b[0])?'background:#fff7ed':'opacity:.6'}"><div style="font-size:34px">${b[2]}</div><h3>${b[1]}</h3><p class=muted>${p.badges.includes(b[0])?'已获得':'继续努力'}</p></div>`).join('')}</div></section></main>`}
function go(v){state.view=v==='map'?'home':v;state.mode='lesson';render()}function openLesson(id){state.lesson=id;state.view='lesson';state.mode='lesson';render()}function startQuiz(){state.view='quiz';state.mode='lesson';state.qi=0;orderPicked=[];render()}function startDaily(){state.view='quiz';state.mode='daily';state.qi=0;orderPicked=[];render()}function nextQ(){state.qi++;orderPicked=[];render()}function clearWrong(id){const p=load();delete p.wrong[id];save(award(p));render()}function review(id){const q=questions.find(x=>x.id===id);state.lesson=q.lessonId;state.mode='lesson';state.qi=questions.filter(x=>x.lessonId===q.lessonId).findIndex(x=>x.id===id);state.view='quiz';render()}function esc(s){return String(s).replaceAll("'","\\'")}render();
