const lessons=[
['what-is-sentence','什么是句子','句子 = 能说完整意思的一句话。','有头有尾意思清，完整一句才叫句。','The bird sings.','这句话说完整了吗？','说完整了：鸟在唱歌。','如果一句话让别人听完还想问“然后呢？”，它可能还不是完整句子。'],
['subject','什么是主语','一句话里，谁在做事，谁就是主语。','谁做事，谁站前，主语主语先出现。','The cat runs.','谁在跑？','cat','主语就像舞台上的主角。先找到主角，再看它做了什么。'],
['verb','什么是动词','动词 = 告诉我们“做什么”或“怎么样”的词。','动作状态找一找，动词马上跑出来。','Lily dances.','Lily 做什么？','dances','跑、吃、看、喜欢、是、变得，这些都能让句子动起来。'],
['object','什么是宾语','动作做到了谁或什么东西身上，谁就是宾语。','动作打到谁身上，谁就坐到宾语旁。','Tom eats apples.','吃了什么？','apples','找宾语时，可以问“做了谁？”“做了什么？”。'],
['sv','主语 + 动词','有些句子只要“谁 + 做什么”，意思就完整。','主语动词手牵手，短句也能说清楚。','Birds fly.','谁 + 做什么？','Birds + fly','run、sleep、swim、fly 这类动作常常自己就能讲清楚。'],
['svo','主语 + 动词 + 宾语','如果动作后面要接“做了什么”，就用主语 + 动词 + 宾语。','谁做事，做什么，SVO 排整齐。','Amy reads books.','Amy 读什么？','books','很多动作像 eat、like、read、make 后面常常要接一个东西。'],
['five-patterns','五大基本句型儿童版','英语句子常见的骨架，可以先看成五种积木搭法。','句子积木五种搭，先找主语别害怕。','I am happy. / I like dogs.','这两句骨架一样吗？','不一样','先不用背复杂名字，先会看骨架：谁、做什么、是什么、给谁、变成什么。']
].map((x,i)=>({id:x[0],title:x[1],one:x[2],chant:x[3],sentence:x[4],q:x[5],a:x[6],life:x[7],examples:['Tom runs.','The dog sleeps.','We read books.'].map((s,j)=>({sentence:s,question:['谁在做事？','做什么？','完整吗？'][j],answer:['看主语','看动词','能说清楚'][j],note:'先找谁，再找动作。'})),idx:i+1}));
const q=[
['what-is-sentence','choice','Which one is a complete sentence?',['A red bag','The rabbit jumps.','Very happy'],'The rabbit jumps.','完整句子','太棒了！有“谁”和“做什么”。','完整句子要让别人听懂一件完整的事。'],
['what-is-sentence','tf','“My dog sleeps.” is a complete sentence.',[],'true','完整句子','对！My dog 是谁，sleeps 是做什么。','它是完整句子。'],
['what-is-sentence','fill','Complete: The sun ___.',[],'shines','完整句子','很好！The sun shines.','这里需要一个动作词。'],
['what-is-sentence','order','Put the words in order.',['runs','The','boy'],['The','boy','runs'],'完整句子','正确！The boy runs.','先说谁，再说做什么。'],
['what-is-sentence','detective','Tap the missing-place clue.',['The','fish','___'],'___','完整句子','对！空格里要放动作。','句子有“谁”，现在缺“做什么”。'],
['subject','choice','In “Tom runs.”, who is the subject?',['Tom','runs','Tom runs'],'Tom','主语','太棒了！Tom 是做事的人。','谁在跑？答案就是主语。'],
['subject','fill','In “The cat sleeps.”, the subject is ___.',[],'The cat','主语','对！The cat 是睡觉的小主角。','找“谁在睡觉”。'],
['subject','tf','In “My sister reads.”, “reads” is the subject.',[],'false','主语','正确！reads 是动作。','主语是 My sister。'],
['subject','detective','Tap the subject.',['The','happy','boy','sings'],'boy','主语','很好！boy 是做事的人。','找“谁在唱歌”。'],
['verb','choice','In “Lily dances.”, which word is the verb?',['Lily','dances','Lily dances'],'dances','动词','对！dances 告诉我们做什么。','动词表示动作或状态。'],
['verb','fill','Complete: We ___ games.',[],'play','动词','很好！play 是动作。','这里需要一个动作词。'],
['verb','tf','“is” can be a verb.',[],'true','动词','对！is 可以说明怎么样。','be 动词也是动词。'],
['verb','detective','Tap the verb.',['The','sky','is','blue'],'is','动词','好眼力！is 是 be 动词。','is 说明天空怎么样。'],
['object','choice','In “Tom eats apples.”, what is the object?',['Tom','eats','apples'],'apples','宾语','对！吃了什么？apples。','宾语是动作做到的东西。'],
['object','fill','In “I like music.”, the object is ___.',[],'music','宾语','正确！喜欢什么？music。','问“喜欢什么？”就能找到宾语。'],
['object','detective','Tap the object.',['Dad','buys','milk'],'milk','宾语','对！买了什么？milk。','宾语回答“做了什么东西”。'],
['sv','choice','Which sentence is S + V?',['Birds fly.','I like apples.','She is kind.'],'Birds fly.','主语 + 动词','对！Birds + fly。','S + V 只有“谁 + 做什么”。'],
['sv','order','Make an S + V sentence.',['sleep','Cats'],['Cats','sleep'],'主语 + 动词','对！Cats sleep.','S + V 顺序：谁 + 做什么。'],
['sv','detective','Tap the verb.',['The','bell','rings'],'rings','主语 + 动词','正确！rings 是动词。','钟做什么？rings。'],
['svo','choice','Which sentence is S + V + O?',['I smile.','Amy reads books.','The sky is blue.'],'Amy reads books.','主语 + 动词 + 宾语','对！Amy + reads + books。','SVO 要有“谁 + 做什么 + 做到了什么”。'],
['svo','order','Make an S + V + O sentence.',['books','reads','Nina'],['Nina','reads','books'],'主语 + 动词 + 宾语','正确！Nina reads books.','顺序是：谁 + 做什么 + 做什么东西。'],
['svo','detective','Tap the object.',['Mom','buys','milk'],'milk','主语 + 动词 + 宾语','对！milk 是宾语。','买了什么？milk。'],
['five-patterns','choice','“I smile.” is closest to which pattern?',['S + V','S + V + O','S + be + adjective'],'S + V','五大基本句型','对！I + smile。','smile 后面不需要接宾语。'],
['five-patterns','match','Match the sentence to its pattern.',['I smile.','I like dogs.','I am happy.'],{'I smile.':'S + V','I like dogs.':'S + V + O','I am happy.':'S + be + adjective'},'五大基本句型','配对成功！你会看句子骨架了。','先找主语和动词，再看后面接了什么。'],
['five-patterns','timed','10 秒挑战：Which sentence means “谁是什么样”？',['I swim.','I am tired.','I read books.'],'I am tired.','五大基本句型','五大句型小勇士！','找 be + 形容词的句子。']
].map((x,i)=>({id:'q'+i,lessonId:x[0],type:x[1],prompt:x[2],options:x[3],answer:x[4],point:x[5],good:x[6],bad:x[7]}));
const badges=[['subject','主语达人','⭐'],['verb','动词达人','⚡'],['all','句子小勇士','🏰'],['detective','语法侦探','🔎'],['wrong','错题清零达人','✨']];
const state={view:'home',lesson:lessons[0].id,qi:0,selected:null};
const load=()=>JSON.parse(localStorage.gck||'{"done":[],"answers":{},"wrong":{},"badges":[]}');
const save=p=>{localStorage.gck=JSON.stringify(p)};
const norm=v=>Array.isArray(v)?v.join(' ').toLowerCase():typeof v==='object'?JSON.stringify(v):String(v).trim().toLowerCase();
const correct=(qq,a)=>norm(qq.answer)===norm(a);
function award(p){if(p.done.includes('subject'))p.badges=[...new Set([...p.badges,'subject'])];if(p.done.includes('verb'))p.badges=[...new Set([...p.badges,'verb'])];if(p.done.length>=7)p.badges=[...new Set([...p.badges,'all'])];if(q.filter(x=>x.type==='detective'&&p.answers[x.id]).length>=3)p.badges=[...new Set([...p.badges,'detective'])];if(Object.keys(p.wrong).length===0&&Object.keys(p.answers).length)p.badges=[...new Set([...p.badges,'wrong'])];return p}
function render(){const p=load();document.getElementById('app').innerHTML=`<header class=top><div class=top-inner><button class=brand onclick="go('home')"><span>Grammar Club Kids</span><strong>英语语法闯关乐园</strong></button><nav class=nav><button onclick="go('home')">首页</button><button onclick="go('wrong')">错题</button><button onclick="go('badges')">徽章</button></nav></div></header>${body(p)}<nav class=bottom><div><button onclick="go('home')">首页</button><button onclick="go('map')">地图</button><button onclick="go('wrong')">错题</button><button onclick="go('badges')">徽章</button></div></nav>`}
function body(p){if(state.view==='lesson')return lessonPage(p);if(state.view==='quiz')return quizPage(p);if(state.view==='wrong')return wrongPage(p);if(state.view==='badges')return badgesPage(p);return homePage(p)}
function homePage(p){const next=lessons.find(l=>!p.done.includes(l.id))||lessons[0];const ans=Object.keys(p.answers).length,ok=Object.values(p.answers).filter(Boolean).length;return `<main><section class=hero><div class=hero-row><div><span class=pill>Grammar Kingdom</span><h1>英语语法王国</h1><p>用卡片学习，用练习闯关，用错题复习，把英语句子看得越来越清楚。</p></div><button class=primary onclick="openLesson('${next.id}')">继续闯关 →</button></div></section><section class="grid stats"><div class=card><h3>今日任务</h3><p class=muted>完成 3 个小关卡</p></div><div class=card><h3>当前进度</h3><p class=muted>${p.done.length}/7 关 · 正确率 ${ans?Math.round(ok/ans*100):0}%</p></div><button class=card onclick="go('wrong')"><h3>我的错题</h3><p class=muted>${Object.keys(p.wrong).length} 道需要复习</p></button><button class=card onclick="go('badges')"><h3>我的徽章</h3><p class=muted>${p.badges.length} 枚已获得</p></button></section>${map(p)}</main>`}
function map(p){return `<section class=card><h2>学习地图</h2><div class="card soft-sky"><strong>句子村 Sentence Village</strong><p class=muted>先学会看懂一句话里面谁在做事、做了什么、做到了谁身上。</p></div><div class="grid map">${lessons.map(l=>`<button class="lesson-btn ${p.done.includes(l.id)?'done':''}" onclick="openLesson('${l.id}')"><span class=num>${p.done.includes(l.id)?'✓':l.idx}</span><span><strong>${l.title}</strong><br><small>${l.one}</small></span></button>`).join('')}</div><div class=soon>${['名词城','代词岛','动词镇','时态森林','形容词花园','副词小路','介词峡谷','句型迷宫'].map(x=>`<div>🔒 ${x}</div>`).join('')}</div></section>`}
function lessonPage(){const l=lessons.find(x=>x.id===state.lesson);return `<main><button class=pill onclick="go('home')">返回地图</button><section class=card><p class=muted>学习卡片</p><h1>${l.title}</h1><div class="grid lesson-hero"><div class="card soft-sky"><b>一句话讲清楚</b><p class=big>${l.one}</p></div><div class="card soft-peach"><b>口诀</b><p class=big>${l.chant}</p></div></div><div class="card soft-mint"><b>图像化例子</b><h2>${l.sentence}</h2><div class="grid example-grid"><div class=card><small>问题</small><p>${l.q}</p></div><div class=card><small>答案</small><p>${l.a}</p></div><div class=card><small>所以</small><p>先找谁，再找动作。</p></div></div></div><div class=card><b>生活化理解</b><p>${l.life}</p></div><div class="grid example-grid">${l.examples.map(e=>`<div class=card><h3>${e.sentence}</h3><p>${e.question}</p><b>${e.answer}</b><p class=muted>${e.note}</p></div>`).join('')}</div><button class=primary onclick="startQuiz()">开始练习</button></section></main>`}
function quizPage(p){const list=q.filter(x=>x.lessonId===state.lesson);if(state.qi>=list.length){let p=load();if(!p.done.includes(state.lesson))p.done.push(state.lesson);save(award(p));return `<main><section class=card style="text-align:center"><h1>小关卡完成</h1><p class=muted>休息一下眼睛，再继续下一关。</p><button class=primary onclick="go('home')">回到学习地图</button></section></main>`}const qq=list[state.qi];let input='';if(['choice','timed'].includes(qq.type))input=qq.options.map(o=>`<button class="choice ${state.selected===o?'selected':''}" onclick="answer('${esc(o)}')">${o}</button>`).join('');if(qq.type==='tf')input=`<button class=choice onclick="answer('true')">正确</button><button class=choice onclick="answer('false')">错误</button>`;if(qq.type==='fill')input=`<input class=input id=fill placeholder="输入答案"><button class=primary onclick="answer(document.getElementById('fill').value)">提交</button>`;if(qq.type==='order')input=`<div class=card id=order>点击词块排序</div><div class=row>${qq.options.map(o=>`<button class=word onclick="pick('${esc(o)}')">${o}</button>`).join('')}</div><button class=primary onclick="answer(orderPicked)">提交</button>`;if(qq.type==='detective')input=`<div class=row>${qq.options.map(o=>`<button class=token onclick="answer('${esc(o)}')">${o}</button>`).join('')}</div>`;if(qq.type==='match')input=`<div class=grid>${qq.options.map(o=>`<label class=card>${o}<select class=input data-match="${o}"><option></option><option>S + V</option><option>S + V + O</option><option>S + be + adjective</option></select></label>`).join('')}</div><button class=primary onclick="answer(Object.fromEntries([...document.querySelectorAll('[data-match]')].map(s=>[s.dataset.match,s.value])))">提交配对</button>`;return `<main><button class=pill onclick="go('lesson')">返回学习卡</button><section class=card><p class=muted>第 ${state.qi+1}/${list.length} 题 · ${qq.point}</p><h2>${qq.prompt}</h2><div class=grid>${input}</div><div id=fb></div></section></main>`}
let orderPicked=[];function pick(x){orderPicked.push(x);document.getElementById('order').textContent=orderPicked.join(' ')}
function answer(a){const p=load(),qq=q.filter(x=>x.lessonId===state.lesson)[state.qi],ok=correct(qq,a);p.answers[qq.id]=ok;if(ok)delete p.wrong[qq.id];else p.wrong[qq.id]={questionId:qq.id,prompt:qq.prompt,wrongAnswer:norm(a),correctAnswer:norm(qq.answer),knowledgePoint:qq.point,mistakeCount:(p.wrong[qq.id]?.mistakeCount||0)+1,lastMistakeAt:new Date().toISOString()};save(award(p));document.getElementById('fb').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><b>${ok?'太棒了！':'再想想'}</b><p>${ok?qq.good:qq.bad}</p>${ok?'':`<p>正确答案：${norm(qq.answer)}</p>`}<button class=primary onclick="nextQ()">下一题</button></div>`}
function wrongPage(p){const r=Object.values(p.wrong);return `<main><section class=card><h2>我的错题</h2>${r.length?r.map(x=>`<div class=wrong><b>${x.knowledgePoint}</b><p>${x.prompt}</p><p>你的答案：${x.wrongAnswer}</p><p>正确答案：${x.correctAnswer}</p><button class=pill onclick="review('${x.questionId}')">重新练习</button><button class=pill onclick="clearWrong('${x.questionId}')">已掌握</button></div>`).join(''):'<div class="card soft-mint"><h2>今天没有错题</h2><p>继续闯关，保持这个状态。</p></div>'}</section></main>`}
function badgesPage(p){return `<main><section class=card><h2>我的徽章</h2><div class="grid map">${badges.map(b=>`<div class=card style="${p.badges.includes(b[0])?'background:#fff7ed':'opacity:.6'}"><div style="font-size:34px">${b[2]}</div><h3>${b[1]}</h3><p class=muted>${p.badges.includes(b[0])?'已获得':'继续努力'}</p></div>`).join('')}</div></section></main>`}
function go(v){state.view=v==='map'?'home':v;state.selected=null;render()}function openLesson(id){state.lesson=id;state.view='lesson';render()}function startQuiz(){state.view='quiz';state.qi=0;orderPicked=[];render()}function nextQ(){state.qi++;orderPicked=[];render()}function clearWrong(id){const p=load();delete p.wrong[id];save(award(p));render()}function review(id){const qq=q.find(x=>x.id===id);state.lesson=qq.lessonId;state.qi=q.filter(x=>x.lessonId===qq.lessonId).findIndex(x=>x.id===id);state.view='quiz';render()}function esc(s){return String(s).replaceAll("'","\\'")}render();
